name: Rotate Secrets

on:
  schedule:
    - cron: "0 3 * * *"
  workflow_dispatch:

jobs:
  rotate:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - run: bash scripts/rotate-secrets.sh
        env:
          GH_TOKEN: ${{ secrets.GH_TOKEN }}
          FLY_API_TOKEN: ${{ secrets.FLY_API_TOKEN }}
          VERCEL_TOKEN: ${{ secrets.VERCEL_TOKEN }}
